import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import React, { ReactNode } from 'react';

import './globals.css';

const rubik = Rubik({
	variable: '--font-rubik-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body className={rubik.variable}>{children}</body>
		</html>
	);
}
